require('dotenv').config();
const express=require('express');
const path=require('path');
const https=require('https');
const PaytmChecksum=require('paytm-pg-node-sdk').PaytmChecksum;
const app=express();app.use(express.json());app.use(express.urlencoded({extended:true}));app.use(express.static(__dirname));
const PORT=process.env.PORT||3000;
const plans={starter:99,pro:199,elite:299};
const host=process.env.PAYTM_ENVIRONMENT==='PRODUCTION'?'https://securegw.paytm.in':'https://securegw-stage.paytm.in';
function postJson(url,payload){return new Promise((resolve,reject)=>{const u=new URL(url);const req=https.request({hostname:u.hostname,path:u.pathname+u.search,method:'POST',headers:{'Content-Type':'application/json','Content-Length':Buffer.byteLength(payload)}},r=>{let d='';r.on('data',c=>d+=c);r.on('end',()=>{try{resolve(JSON.parse(d))}catch(e){reject(new Error('Invalid Paytm response'))}})});req.on('error',reject);req.write(payload);req.end()})}
app.post('/api/paytm/initiate',async(req,res)=>{try{if(!process.env.PAYTM_MID||!process.env.PAYTM_MERCHANT_KEY) return res.status(500).json({error:'Paytm is not configured yet.'});const {plan,email,name}=req.body;const amount=plans[plan];if(!amount||!email) return res.status(400).json({error:'Invalid plan/account.'});const orderId='EXAMY_'+Date.now()+'_'+Math.random().toString(36).slice(2,7);const body={requestType:'Payment',mid:process.env.PAYTM_MID,websiteName:process.env.PAYTM_WEBSITE||'WEBSTAGING',orderId,callbackUrl:(process.env.BASE_URL||'http://localhost:'+PORT)+'/api/paytm/callback',txnAmount:{value:amount.toFixed(2),currency:'INR'},userInfo:{custId:'EXAMY_'+Buffer.from(email).toString('base64').replace(/[^a-zA-Z0-9]/g,'').slice(0,30),firstName:name||'Student'}};const signature=await PaytmChecksum.generateSignature(JSON.stringify(body),process.env.PAYTM_MERCHANT_KEY);const payload=JSON.stringify({body,head:{signature}});const data=await postJson(host+'/theia/api/v1/initiateTransaction?mid='+encodeURIComponent(process.env.PAYTM_MID)+'&orderId='+encodeURIComponent(orderId),payload);const token=data?.body?.txnToken;if(!token) return res.status(502).json({error:data?.body?.resultInfo?.resultMsg||'Paytm did not return a transaction token.'});res.json({success:true,orderId,txnToken:token,amount:amount.toFixed(2),checkoutJsUrl:(process.env.PAYTM_ENVIRONMENT==='PRODUCTION'?'https://securegw.paytm.in':'https://securegw-stage.paytm.in')+'/merchantpgpui/checkoutjs/merchants/'+process.env.PAYTM_MID+'.js'});}catch(e){console.error(e);res.status(500).json({error:e.message})}});
app.post('/api/paytm/callback',async(req,res)=>{try{const data=req.body||{};const checksum=data.CHECKSUMHASH;const params={...data};delete params.CHECKSUMHASH;const valid=await PaytmChecksum.verifySignature(params,process.env.PAYTM_MERCHANT_KEY,checksum);if(!valid)return res.status(400).send('Checksum verification failed');const orderId=data.ORDERID||'';const status=data.STATUS||'';if(status==='TXN_SUCCESS'){return res.redirect('/success.html?orderId='+encodeURIComponent(orderId))}return res.redirect('/checkout.html?payment=failed&orderId='+encodeURIComponent(orderId));}catch(e){console.error(e);res.status(500).send('Payment callback error')}});
app.post('/api/upi/submit',(req,res)=>{try{const {plan,email,name,exam,utr}=req.body;const amounts={starter:99,pro:199,elite:299};if(!amounts[plan]||!email||!utr)return res.status(400).json({error:'Plan, email and UTR are required.'});const record={id:'UPI_'+Date.now(),plan,amount:amounts[plan],email,name:name||'',exam:exam||'',utr:String(utr).trim(),status:'PENDING',createdAt:new Date().toISOString()};console.log('[UPI PAYMENT PENDING]',record);res.json(record)}catch(e){res.status(500).json({error:e.message})}});
app.get('/health',(req,res)=>res.json({ok:true,service:'EXAMYWEB'}));app.listen(PORT,()=>console.log('EXAMYWEB running on http://localhost:'+PORT));
